server:
  port: 8088
  servlet:
    context-path: /consumer
    encoding:
      charset: utf-8
      force: true
      enabled: true
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8192


management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - beans
          - health

Feign:
  hystrix:
    enabled: true