server:
  port: 9099
  servlet:
    context-path: /provider
    encoding:
      charset: utf-8
      force: true
      enabled: true
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 1000
    max-http-header-size: 8192

spring:
  application:
    name: defaultProvider

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:1011/eureka/

